apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 762233746723.dkr.ecr.us-east-1.amazonaws.com/backend-repo:cf859b21
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_USER
              value: task_manager
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: task_manager
            - name: POSTGRES_HOST
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskmanager
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

