apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskmanager
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # Base64-encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # Base64-encoded 'password'
  POSTGRES_DB: dGFza21hbmFnZXI= # Base64-encoded 'taskmanager'

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: taskmanager
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres # Host path to store data
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: taskmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: taskmanager
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

