# Frontend Service (frontend-service.yaml)
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: taskmanager
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000