apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: taskmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
