frontend:
  replicaCount: 1
  image: 762233746723.dkr.ecr.us-east-1.amazonaws.com/frontend-repo:ace0f7f3
  REACT_APP_BACKEND_URL: "http://ingress-nginx.ingress-nginx.svc.cluster.local"
  service:
    port: 3000

backend:
  replicaCount: 1
  image: 762233746723.dkr.ecr.us-east-1.amazonaws.com/backend-repo:ace0f7f3
  service:
    port: 5001

database:
  replicaCount: 1
  image: postgres:15
  service:
    port: 5432
  storage:
    size: 2Gi
    mountPath: /var/lib/postgresql/data
    hostPath: /mnt/data/postgres 

global:
  secret:
    username: task_manager
    password: password
    db: task_manager
