apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-frontend-config
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "9"
data:
  REACT_APP_BACKEND_URL: {{ .Values.frontend.REACT_APP_BACKEND_URL }}
