apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}-frontend
  labels:
    app: {{ include "mychart.name" . }}
    tier: frontend
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "10"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mychart.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "mychart.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        # env:
        #   - name: REACT_APP_BACKEND_URL
        #     value: "http://aafb445dd59aa4c14a34eff8cf00bdc0-1609540402.us-east-1.elb.amazonaws.com/backend"