apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-controller
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "9"
spec:
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      containers:
        - name: nginx-ingress
          image: nginx
