apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-database-pvc
  annotations:
     "helm.sh/hook": "pre-install"
     "helm.sh/hook-weight": "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
  volumeName: {{ include "mychart.fullname" . }}-database-pv