apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-secret
  annotations:
     "helm.sh/hook": "pre-install"
     "helm.sh/hook-weight": "1"
type: Opaque
data:
  POSTGRES_USER: {{ .Values.global.secret.username | b64enc }}  # Base64 encoded value of "task_manager"
  POSTGRES_PASSWORD: {{ .Values.global.secret.password | b64enc }} # Base64 encoded value of "password"
  POSTGRES_DB: {{ .Values.global.secret.db | b64enc }}     # Base64 encoded value of "task_manager"