apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-backend
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "7"
  labels:
    app: {{ include "mychart.fullname" . }}-backend
spec:
  selector:
    app: {{ include "mychart.fullname" . }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
