apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskmanager
type: Opaque
data:
  POSTGRES_USER: dGFza19tYW5hZ2Vy   # Base64 encoded value of "task_manager"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=   # Base64 encoded value of "password"
  POSTGRES_DB: dGFza19tYW5hZ2Vy     # Base64 encoded value of "task_manager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: taskmanager
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pv
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc